package com.guts.Guts_IAM.auditlog.action;

public enum Action {
    LOGIN,
    REFRESH_TOKEN, SESSION_REVOKE, REFRESH_TOKEN_CREATED, LOGOUT,
    VERIFY_OTP, LOGOUT_ALL, SEND_OTP, ACCOUNT_UNLOCK, SEND_VERIFICATION_EMAIL, VERIFY_EMAIL, SIGNUP,
    RESET_PASSWORD, FORGOT_PASSWORD
}
