package com.guts.Guts_IAM.auditlog.action;

public enum Action {
    LOGIN,
    REFRESH_TOKEN, SESSION_REVOKE, REFRESH_TOKEN_CREATED, LOGOUT,
    VERIFY_OTP, LOGOUT_ALL, SEND_OTP, ACCOUNT_UNLOCK, SEND_VERIFICATION_EMAIL, VERIFY_EMAIL, SIGNUP,
    RESET_PASSWORD, REFRESH_ACCESS_TOKEN, VIEW_PROFILE, UPDATE_PROFILE, VIEW_LOGS, VIEW_ALL_ACTIVE_USER, UPDATE_USER_STATUS, VIEW_ALL_AUDIT_LOG, ADDED_NEW_ROLE, DOWNLOAD_AUDIT_LOG, FORGOT_PASSWORD,EMAIL_VERIFIED,SIGN_UP_PENDING
}
